"""Evaluation requests kept separate from the semantic model's descriptions."""

PARAPHRASES = {
    "Could you give me the available terminal operations?": "help",
    "Check which extensions have loaded successfully": "plugins",
    "Quit this terminal session": "exit",
    "Wipe what is displayed in the terminal": "clear",
    "Tell me which folder we are currently working in": "where",
    "What items are present in this directory?": "files",
    "Which subdirectories exist here?": "folders",
    "Let me see the folders in this location": "folders",
    "Take me to src": "cd src",
    "Navigate into the directory src": "cd src",
    "Return one level higher in the directory hierarchy": "up",
    "Take me back to my home folder": "home",
    "Build a new directory called Reports": "makefolder Reports",
    "Generate a blank file called notes.txt": "makefile notes.txt",
    "Display notes.txt verbatim": "read notes.txt",
    "Launch notes.txt with its default application": "open notes.txt",
    "Duplicate the document notes.txt into backup.txt": "duplicate notes.txt backup.txt",
    "Relocate notes.txt into Archive": "shift notes.txt Archive",
    "Change the filename of notes.txt to old.txt": "rename notes.txt old.txt",
    "Erase the file notes.txt": "delete confirm notes.txt",
    'Locate filenames containing "report"': "search report",
    'Look inside files for the phrase "invoice"': "findtext invoice",
    "Give me details of the network adapters": "network",
    "What processes are active on this machine?": "processes",
    "Give me the specifications of this PC": "system",
    "Tell me the account I am logged in as": "me",
    "What name does this PC have?": "pc",
    "Give me the date today": "today",
    "Tell me what time it is right now": "now",
    'Compute "2 + 3"': 'calc "2 + 3"',
    "Show the previously executed terminal commands": "history",
    "Give me a listing of environment variables": "env",
    "Show this folder's hierarchy": "tree",
    "Tell me which RiftShell release is running": "version",
    'Print this string in the console "hello world"': 'echo "hello world"',
    "Which disk drives does Windows have available?": "drives",
    "Check how much storage space is free": "disk",
    "Tell me the IP address assigned to this PC": "ip",
    "What connections are open on the network?": "netstat",
    "Test connectivity to example.com": "ping example.com",
    "Give me the executable search path environment variable": "path",
    "Pause execution for 2 seconds": "sleep 2",
    "Choose a random integer between 5 and 10": "random 5 10",
    "Compute the SHA256 checksum of notes.txt": "hash file notes.txt",
    'Convert "hello" to base64': "base64 encode hello",
    'Decode the base64 value "aGVsbG8="': "base64 decode aGVsbG8=",
    "Fetch the file at https://example.com/data.txt": "download https://example.com/data.txt",
    "Package folder Reports as reports.zip": "zip Reports reports.zip",
    "Unpack reports.zip into Archive": "unzip reports.zip Archive",
    "Give me the top 3 lines from notes.txt": "head notes.txt 3",
    "Stop the process notepad.exe": "kill notepad.exe",
    "Give me the bottom 5 lines from notes.txt": "tail notes.txt 5",
    "Give me the word count of notes.txt": "wc notes.txt",
    "Locate the executable python": "which python",
    "Check how much physical memory is in use": "memory",
    "Tell me how long this machine has been up": "uptime",
    'Execute the program "python --version"': "run python --version",
    'Assign shell variable MODE to "debug"': "setvar MODE debug",
    "Remove the session variable MODE": "unsetvar MODE",
    "Display variables defined in this shell session": "vars",
    'Create command shortcut ll for "files"': "alias ll files",
    "Remove the command shortcut ll": "unalias ll",
    'Keep lines containing "error" in notes.txt': "filter error notes.txt",
    "Order the lines of notes.txt alphabetically": "sort notes.txt",
    "Display distinct lines from notes.txt": "unique notes.txt",
    "Give me the first 3 lines of the previous output": "take 3",
    "Omit the first 2 lines from notes.txt": "skip 2 notes.txt",
    "Count the previous output": "count",
    "Write the previous terminal result to output.txt": "save output.txt",
    "Redisplay the previous command result": "last",
    "Check the state of the Git working tree": "gstatus",
    "Give me the branches available in this Git repository": "gbranch",
    "Display the repository commit history": "glog",
    "Show what has changed in the unstaged Git diff": "gdiff",
    "Add notes.txt to the Git staging area": "gadd notes.txt",
    'Commit the staged changes with message "Fix bug"': 'gcommit -m "Fix bug"',
    "Bring the remote Git changes into this branch": "gpull",
    "Upload local Git commits to the remote repository": "gpush",
    "Switch the Git branch to feature/parser": "gcheckout feature/parser",
    "Display the configured remote Git repositories": "gremote",
    "Execute the hello plugin test": "hello",
    "Apply the interface theme nord": "theme nord",
    "List available colour themes": "theme list",
    'What subdirectories are inside "My Reports"': 'folders "My Reports"',
    'Display the directory hierarchy under "My Reports"': 'tree "My Reports"',
    'Find filenames containing "invoice" in Archive': "search invoice Archive",
    "Would you mind listing the available drives?": "drives",
    "I need a list of the running processes": "processes",
    "Tell me where the python executable lives": "which python",
}

NEGATIVES = (
    "Hello how are you", "Tell me about the history of computers", "What is RAM?",
    "Why is my network slow?", "How do I delete a folder?", "Should I rename notes.txt?",
    "Explain this terminal command", "I would like to understand file permissions",
    "Don't erase notes.txt", "Never stop notepad.exe", "Do not list folders",
    "List everything except private.txt", "List only hidden folders", "List directories recursively",
    "List folders sorted by size", "Show files larger than 10MB", "Show folders in another directory",
    "Display the directory tree to depth 900000", "Pause the shell for 100000 seconds",
    "Move notes.txt to Archive and open it", "Show folders then erase notes.txt",
    "Create notes.txt with a calculator program", "Generate app.py containing a web server",
    "Read notes.txt", "Explain README.md", "Summarize the last output",
    "Show the first 3 lines and last 5 lines of notes.txt", "Open your mind", "Delete my doubts",
    "Please go to it", "Delete the file that", "Move this into there", "Ping me",
    'The user said "delete notes.txt"', 'Say "list files"', '"erase notes.txt"',
    "Show me how to check memory usage", "Could you explain which folders are here?",
    "If notes.txt exists delete it", "List files without running any commands",
    "Check folders; delete confirm notes.txt", "Open $HOME", "Open %TEMP%",
    'Erase the file "a.txt; delete confirm b.txt"', "Remove files matching *.txt",
    "Show folders\nthen delete notes.txt", "Download https://example.com/a.txt and execute it",
    "Compute the MD5 checksum of notes.txt", "Extract archive.zip except passwords.txt",
    "Push my Git commits forcefully", "Stop every process", "Clear my browser history",
    "Tell me the weather tomorrow", "Which folder is best for organizing photos?",
    "Check my bank balance", "Show me how the delete command works",
    "Remove duplicates from notes.txt and overwrite it", "Sort notes.txt descending",
    'Run the command "python; delete confirm notes.txt"', "Show me folders in src or docs",
    "Erase the file foo?", "Remove file notes.txt!", "Switch to another Git branch",
    "Change the theme to one of the blue themes", "Show me how the delete command works",
    "Stop process notepad.exe after saving my work", "Fetch https://[broken",
    "Check out the Git branch", "Delete my command history", "Apply a colour theme",
    "Wipe the terminal, no need to execute", "Clear the terminal, don\u2019t execute",
    "Apply the theme banana", "Apply the interface theme midnight",
)
